




[general]

project_name       = "Engagement 1"


data_dir           = "~/.local/share/four-hub"



extra_tools_paths  = []


[crypto]

m_cost   = 65536
t_cost   = 3
p_cost   = 1



salt_hex = ""


[network]

use_proxychains    = false
proxychains_bin    = "proxychains4"


[stealth]

process_name       = "kworker/2:1"


anti_forensics     = true


mlock_memory       = true



randomise_mac_iface = ""


[ui]

theme              = "cyberpunk"


fps                = 30


enable_mouse       = true


[api]

enabled            = false
bind               = "127.0.0.1:7878"


[logging]

log_dir            = "~/.local/share/four-hub/logs"


level              = "info"
